functionName: song-efs-nio
active: four_384_well_plates
inputMap:
  custom:
    numLambdas: 1
    namePrefix: song-test
    numFiles: 1
    numThreads: 1
    directory: /home/ec2-user/efs
    bufferSize: 5120
    fileSize: 1
  four_384_well_plates:
    numLambdas: 2992
    namePrefix: four_384_well_plates
    numFiles: 2
    numThreads: 2
    directory: /home/ec2-user/efs
    bufferSize: 5120
    fileSize: 48
  800_channel_1_file:
    numLambdas: 2400
    namePrefix: 800_channel_1_file
    numFiles: 600
    numThreads: 50
    directory: /home/ec2-user/efs
    bufferSize: 5120
    fileSize: 157
  large_amgen:
    numLambdas: 3960
    namePrefix: large_amgen
    numFiles: 1
    numThreads: 1
    directory: /home/ec2-user/efs
    bufferSize: 5120
    fileSize: 782
  5m_events:
    numLambdas: 840
    namePrefix: 5m_events
    numFiles: 21
    numThreads: 21
    directory: /home/ec2-user/efs
    bufferSize: 5120
    fileSize: 40960
log: false