functionName: song-efs-nio
#active: four_384_well_plates
#active: 800_channel_1_file
#active: large_amgen
#active: 5m_events
active: 1m_events
#active: 10m_events
#active: 25m_events
#active: 40m_events
inputMap:
  custom:
    numLambdas: 1
    namePrefix: song-test
    numFiles: 1
    numThreads: 1
    directory: /mnt/channelstripe
    bufferSize: 5120
    fileSize: 1
  four_384_well_plates:
    numLambdas: 2992
    namePrefix: four_384_well_plates
    numFiles: 2
    numThreads: 2
    directory: /mnt/channelstripe
    bufferSize: 5120
    fileSize: 48
  800_channel_1_file:
    numLambdas: 2400
    namePrefix: 800_channel_1_file
    numFiles: 25
    numThreads: 25
    directory: /mnt/channelstripe
    bufferSize: 5120
    fileSize: 157
  large_amgen:
    numLambdas: 3960
    namePrefix: large_amgen
    numFiles: 1
    numThreads: 1
    directory: /mnt/channelstripe
    bufferSize: 5120
    fileSize: 782
  5m_events:
    numLambdas: 840
    namePrefix: 5m_events
    numFiles: 21
    numThreads: 21
    directory: /mnt/channelstripe
    bufferSize: 5120
    fileSize: 40960
  1m_events:
    numLambdas: 1000
    namePrefix: 1m_events
    numFiles: 5
    numThreads: 5
    directory: /mnt/channelstripe
    bufferSize: 5120
    fileSize: 8196
  10m_events:
    numLambdas: 50
    namePrefix: 10m_events
    numFiles: 5
    numThreads: 5
    directory: /mnt/channelstripe
    bufferSize: 5120
    fileSize: 81960
  25m_events:
    numLambdas: 10
    namePrefix: 25m_events
    numFiles: 5
    numThreads: 5
    directory: /mnt/channelstripe
    bufferSize: 5120
    fileSize: 204900
  40m_events:
    numLambdas: 10
    namePrefix: 40m_events
    numFiles: 5
    numThreads: 5
    directory: /mnt/channelstripe
    bufferSize: 5120
    fileSize: 327840
log: true
lambdaInvocationPoolSize: 100