functionName: song-efs-nio
active: four_384_well_plates
#active: 800_channel_1_file
#active: large_amgen
#active: 5m_events
inputMap:
  custom:
    numRequests: 1
    namePrefix: song-test
    numFiles: 1
    numThreads: 1
    directory: /home/ec2-user/efs
    bufferSize: 5120
    fileSize: 1
  four_384_well_plates:
    numRequests: 2992
    namePrefix: four_384_well_plates
    numFiles: 5
    numThreads: 5
    directory: /home/ec2-user/efs
    bufferSize: 5120
    fileSize: 48
  800_channel_1_file:
    numRequests: 2400
    namePrefix: 800_channel_1_file
    numFiles: 5
    numThreads: 5
    directory: /home/ec2-user/efs
    bufferSize: 5120
    fileSize: 157
  large_amgen:
    numRequests: 3960
    namePrefix: large_amgen
    numFiles: 5
    numThreads: 5
    directory: /home/ec2-user/efs
    bufferSize: 5120
    fileSize: 782
  5m_events:
    numRequests: 840
    namePrefix: 5m_events
    numFiles: 5
    numThreads: 5
    directory: /home/ec2-user/efs
    bufferSize: 5120
    fileSize: 40960
log: true
threadsPoolSize: 100